//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_ventas
    {
        public int id { get; set; }
        public Nullable<int> id_venta { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<double> precio { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual productos productos { get; set; }
        public virtual ventas ventas { get; set; }
    }
}
