//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_Compras
    {
        public int id { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<int> id_prov { get; set; }
        public Nullable<int> id_lote { get; set; }
        public Nullable<double> precio_compra { get; set; }
        public Nullable<double> precio_venta { get; set; }
        public Nullable<double> cantidad { get; set; }
        public Nullable<int> id_estado { get; set; }
        public Nullable<int> id_compra { get; set; }
    
        public virtual compras compras { get; set; }
        public virtual estados estados { get; set; }
        public virtual lote lote { get; set; }
        public virtual productos productos { get; set; }
    }
}
