//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_4BitsEntities : DbContext
    {
        public DB_4BitsEntities()
            : base("name=DB_4BitsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clientes> clientes { get; set; }
        public virtual DbSet<compras> compras { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<detalle_Compras> detalle_Compras { get; set; }
        public virtual DbSet<detalle_ventas> detalle_ventas { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<grupos> grupos { get; set; }
        public virtual DbSet<Localidades> Localidades { get; set; }
        public virtual DbSet<lote> lote { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<proveedores> proveedores { get; set; }
        public virtual DbSet<Provincias> Provincias { get; set; }
        public virtual DbSet<rel_UsGr> rel_UsGr { get; set; }
        public virtual DbSet<tipo_Clientes> tipo_Clientes { get; set; }
        public virtual DbSet<tipo_Doc> tipo_Doc { get; set; }
        public virtual DbSet<unidades> unidades { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ventas> ventas { get; set; }
    }
}
