//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedores
    {
        public int id { get; set; }
        public Nullable<int> id_tipoDoc { get; set; }
        public Nullable<int> nro_Doc { get; set; }
        public Nullable<int> id_localidad { get; set; }
        public string razon_Social { get; set; }
        public Nullable<int> cp { get; set; }
        public string telefono { get; set; }
        public string mail { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual Localidades Localidades { get; set; }
        public virtual tipo_Doc tipo_Doc { get; set; }
    }
}
