//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class rel_UsGr
    {
        public int id { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public Nullable<int> id_Grupo { get; set; }
        public Nullable<int> id_estado { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual grupos grupos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
